### ISSUE TITLE
roadmap 0.7

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1934]
preliminary list of things that should or might go into 0.7
see issues for milestone 0.7 for some of the details

Note: We are planning for a short 0.7 release cycle, so prioritizing and trimming will be necessary.
### statsmodels.base, generic
- [ ] consistency of names and definitions, continue from 0.6
  - [ ] fittedvalues, cov_type, ...
  - [ ] possible redefinitions, not fully decided yet, df_model with all parameters, aic, bic, ...
  - [ ] ...
- [ ] `missing` interaction in formulas with patsy
- [ ] dtype problems
- [ ] optimize
  - [ ] open PRs to outsource and make it more flexible
  - [ ] option for automatic reparameterization, see also below
  - [ ] ...
- [ ] fit_regularized, needs review and design and naming consistency
  - [ ] Regression model has fit_regularized already, #1827 
  - [ ] supporting functions, regularization path
- [ ] fit_constrained, not enabled for all models
  - [ ] discrete models need offset
- [ ] score_test, generic setup based on fit_restricted
- [ ] internal reparameterization functions
  - [ ] affine transform for linear restrictions, see fit_constrained, not available in all models, 
     needs cleanup of standalone function
  - [ ] scaling exog array for better optimization
  - [ ] regularization of the exog matrix for singular or near singular problems
- [ ] support creating new model and results instances based on existing ones 
- [ ] start with generic bootstrap support for models (might be only in 0.8)
  - [ ] as cov_type option, similar to cov_bootstrap in GenericLikelihoodModel
  - [ ] bootstrap for hypothesis testing in models, e.g. linear or nonlinear function of parameters in OLS 
### cleanup and refactoring
- [ ] robust
- [ ] GLM, add analytical derivatives for score_obs
- [ ] nonparametric, @Padarn, @PierreBdR 
- [ ] GLM, RLM fit with scipy optimizers
### new models and functions
- [ ] ???

**Comment by josef-pkt** [comment]
I'm preparing for a round of merging PRs, but I lost the overview (66 open PRs right now, 19 are mine)

triage based on what I know/remember and on how close to merge ready

**essentially ready**

- [ ] #2162 ready to merge except for naming
- [ ] #2018  should be ready, quick review, rebase to update (?)
- [ ] #2158  should be ready, quick review, rebase to update (?)
- [ ] #2086  should be ready, quick review, rebase to update (?)
- [ ] #2137 #2143 fixed scale, should be ready, quick review, rebase to update (?)
- [ ] #2132 Wald anova, should be ready, quick review, rebase to update (?)
- [ ] 

**more review**

- [ ] #2090 GEE weights, needs a review, should be ok
- [ ] #1961 GLM with optimize, maybe, not really urgent but should be "innocent"
- [ ] 

**needs work, but feasible**

- [ ] #2151 prediction interval, try to get at least basic version or `regression` version
- [ ] #2030 beta regression, should be close to finished, other changes still in my branch
- [ ] #1935 heckman, still test failure, needs refactoring, incomplete review

- [ ] #2096 score/lm_test  might get too big, not yet for public consumption, try to get basic version in

there are many other PRs that I haven't looked at recently, and don't know enough about the status.
The above is mostly from the first page of the PR list.

**Comment by josef-pkt** [comment]
current testing status

### 2015-01-22 619f88a813009ddd22a8a112802e1db3a7f15c2b
Ubuntu pythonxy all green except nose version (*1) on Trusty  issue #2121
Debian nipy   both green

(*1)
python-nose (1.3.1-2) in both trusty
https://launchpadlibrarian.net/195510809/buildlog_ubuntu-trusty-amd64.statsmodels_0.7.0~ppa25~revno-1795~ubuntu14.04.1_FAILEDTOBUILD.txt.gz

**Comment by josef-pkt** [comment]
@jseabold  can you check why the doc build is not updating the sourceforge site?

I see some errors and warnings in the sphinx build but cannot find the reasons. I'm not very good in deciphering rst/sphinx error messages.

The only two so far: remove ECDF from tools, add version0.7 to release/index.rst

**Comment by jseabold** [comment]
The nightly build box is offline AFAIK, and I don't have access to it. I
can push things automatically from my laptop.

**Comment by josef-pkt** [comment]
statespace is now also green on Ubuntu i386 python-xy, green on one nipy Debian (the other one has wrong version)

I'd like to stop and just get this out, so we can get to 0.8. (There are still open PRs, but we have to stop somewhere.)
release related things are still to do.

we have only 31 closed issues, but 58 closed PRs with milestone 0.7
I added a milestone to a few issues that didn't have one, but I don't think there are many left that should be 0.7 (real issues, not question or invalid issues)

@jseabold  Do you have time to tag and build the binaries this week ?
I will go through the closed PRs to see what else should be added to the release notes.
@chadfulton Can you write (or copy-paste) an announcement to `statsmodels\docs\source\release\version0.7.rst` ?

**Comment by ChadFulton** [comment]
Yes, I will do that tomorrow morning. I will also take a pass at refactoring the results classes to use the wrapper, to hopefully get that in 0.7

**Comment by ChadFulton** [comment]
Has anyone else tried to build the documentation with the state space additions? It builds fine for me, but I don't trust Sphinx. Also I use LaTeX in the notebooks and the Mathjax CDN that gets injected into the output HTML appears to be out-of-date (and so the math does not render) unless the machine building the documentation has a quite recent IPython or has updated the configuration (see https://github.com/ipython/ipython/issues/4432).

**Comment by josef-pkt** [comment]
I built the docs and don't have the correctly rendered math in the notebooks.

**Comment by ChadFulton** [comment]
I don't know how the docs are built for the website, but the fix is to go into the IPython profile configuration and set this variable:

```python
c.NotebookApp.mathjax_url = 'http://cdn.mathjax.org/mathjax/latest/MathJax.js'
```

If you view source on any of the notebooks on the website, you'll see that it attempts to load the MathJax script at the address: https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS_HTML, which no longer exists.

**Comment by ChadFulton** [comment]
Release documentation in #2285

**Comment by ChadFulton** [comment]
> I will also take a pass at refactoring the results classes to use the wrapper, to hopefully get that in 0.7

I think we should leave this to 0.8 because I think it will make more sense to do along with decoupling the inheritance of MLEModel from the state space base classes. Right now it's going to be a little more messy than necessary.

Although I do not really understand what the wrappers accomplish, so maybe I'm not seeing how important this is?

**Comment by josef-pkt** [comment]
about the wrapper: you can look at how Skipper did this for ARIMA.
Essentially we are hiding the conversion to DataFrames and Series in a wrapper class. In your current version you convert it explicitly and have both the numpy version `_params` and the pandas version `params` in the same class. With the wrapper, the underlying results instance, `res._results` is pure numpy. Because you are creating the results instance indirectly, it's a bit more difficult.

**Comment by bashtage** [comment]
@josef-pkt Probably closeable.

**Comment by jbrockmendel** [comment]
Closeable?
