### ISSUE TITLE
SUMM: statespace additions - GSOC 2015

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2467]
overview of PRs by @ChadFulton  for GSOC 2015

see also #2252

general or required by others (merged for 0.7)
- [x] #2356  cov_type - ready to merge ?
- [x] #2461 compatibility BUG - ready to merge ?
- [x] #2461 #2489 small refactoring, compatibility

more on top of existing
- [ ] #2473 refactoring, decoupling
- [ ] #2431 add diagnostic (plot)

new models
- [ ] #2432 unobserved components
- [ ] #2434 Kalman smoother

**Comment by josef-pkt** [comment]
@ChadFulton  I will merge a few high priority bug fixes to master today, then I will start merging for 0.8

question: #2356 and #2461 need to be merged first. Is there a sequence between the two? Does one need to be rebased after the other has been merged?

Is there anything that would be necessary as fix for 0.7?

**Comment by ChadFulton** [comment]
#2356 and #2461 are independent and can be merged in either order. Both are ready for merge from my perspective, but #2356 needs eyes on the code.

#2461 is a bug fix, necessary for 0.7 for Scipy=0.11 users.

#2356 is not a bug *per se* but I think should be in 0.7 if possible since there are many instances where the pre-#2356 behavior will give NaN's in standard errors.

Then, of the other PRs:

Diagnostics (#2431) and smoothing (#2434) depend on the bug fix (#2461).

UC models (#2432) don't depend on any of the above, but I think the example notebooks would be nicer if I had access to smoothing (#2432) and improved covariances (#2356).

**Comment by bashtage** [comment]
Closing as out-of-date.
