### ISSUE TITLE
SUMM: old pull requests

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2503]
An inventory of PRs that have been waiting for a long time

The biggies

- [ ] #304 Nonlinear LS
- [ ] #361 sysreg -> rebased in #2500 
- [ ] #452 robust new estimators
- [ ] #786 repeated measures anova
- [ ] #1120 Conditional Logit and discrete choice -> rebased #1605
- [ ] #1133 Panel Data
- [ ] #1341 robust cleanup, (nonlinear) M-estimators ?
- [ ] #1489 exponential smoothing
- [ ] #1665 Theil/Ridge penalized linear model
- [ ] #1673 Restricted GLS (not so big)
- [ ] #2139 Tobit rebased

and more recent ones

graphics

- [ ] #1388 facet plots

major refactoring and enhancements

- [ ] #308 GOF in sandbox
- [ ] #973 #1678 #1687 nonparametric
- [ ] #1433 probability plots

several smaller functions and classes

BDS test, Johansen cointegration, ...

the rest is 2014 or newer

more in sandbox which also has outdated code and models, that should be deleted or replaced
.

**Comment by kshedden** [comment]
I'm not opposed to merging it, but I wonder if we ultimately will want to maintain the special-case repeated measures ANOVA code when the same models can be fit using MixedLM.  We now have quite efficient handling of variance components, so we can easily fit a balanced or unbalanced 1, 2, 3, ... way ANOVA with arbitrary combinations of fixed and random factors.  To do this, we specify one group, and the calculations are now optimized quite well for that special case.

We don't have a convenience function to do this but I could throw one together quite quickly.  We don't have eta^2, observed power, sphericity tests either, but I don't think those would be difficult to add.

Here is a simple example:

http://nbviewer.ipython.org/urls/umich.box.com/shared/static/rxdtbw8p3tyzmstsan2ic4hzawv5hbq5.ipynb

**Comment by josef-pkt** [comment]
about `repanova`: I also prefer if we could implement in on top of more general models, like `anova_lm` and OLS. (But I still don't know what the equivalent is.) There is a strong demand to get the same results as traditional repanova as for example in SPSS.

AFAICS, repanova uses fixed effects, which might have different properties if the MixedLM assumptions don't hold. but I don't know how this works out if we only have categorical variables instead of a repeated measures ANCOVA structure.

**Comment by jbrockmendel** [comment]
@josef-pkt a few items in the checklist above can be crossed off
