### ISSUE TITLE
GSOC 2016: VECM

### ISSUE THREAD

**Issue by yogabonito** [statsmodels/statsmodels#3013]
Currently I am trying to implement the estimation of VECM parameters.
An issue I haven't solved so far is the integration of deterministic terms (See Lütkepohl (2005) chapters 6.4 and 7.2.4) - the incorporation of seasonal terms seems tricky to me. In his example on p. 303, Lütkepohl defines the vector D_t as (1, s_1, s_2, s_3)' but I haven't found an explanation, where these s_i come from (maybe regression?).
Does anyone know this?

**Comment by josef-pkt** [comment]
I didn't look very closely, but I think they are just seasonal dummies, i.e. indicator variables for 1st, 2nd and 3rd quarter with one quarter dropped as reference case to avoid collinearity/singularity with the constant.

**Comment by josef-pkt** [comment]
Yes, section 7.2.4 just says seasonal or other dummy variables.
If you have a 1-dimensional quarter array, then using numpy you could just do 

`quarter[:, None] = np.unique(quarter)[:-1]`

or replace the unique call with np.arange(3) if quarters are coded 0,1,2,3.
or use patsy or pandas to create the same dummy variables.

**Comment by yogabonito** [comment]
Thanks Josef for your quick reply!
The trick with [:, None] has already saved me some time.
I have sent you an e-mail since I am still having some trouble (the matrix has to have the same width as the matrix \Delta X and my approach yields a different result than JMulTi).

**Comment by josef-pkt** [comment]
open a WIP pull request so I can see what you have, we can clean up the branch later.

WIP = work in progress

(I replied to email with travel details)

**Comment by yogabonito** [comment]
### Todo list / topics from my GSoC proposal:

... related to estimation (chapter 7 in Lütkepohl (2005))
- [ ] Estimation of VECMs
- [ ] Forecasting
- [ ] Testing for Granger-causality
- [ ] Impulse response analysis

... related to specification of VECMs (chapter 8)
- [ ] Lag order selection
- [ ] Testing for the rank of cointegration
- [ ] Checking for residual autocorrelation
- [ ] testing for nonnormality
- [ ] tests for structural change

**Comment by josef-pkt** [comment]
@yogabonito 

can you look at Stata http://www.stata.com/manuals14/tsvec.pdf or R to see what information should be available in output tables, and how you can provide them.
I went through the Stata manual, and one possibly messier part are the **implied** and normalized parameters that don't have standard errors or covariance. I think those can be added separately to the output, so params and cov_params only has the directly estimated params.

**Comment by yogabonito** [comment]
Of course. I will have a look at it tomorrow.

**Comment by josef-pkt** [comment]
more links

SAS seems to have a well featured VECM also
http://support.sas.com/documentation/cdl/en/etsug/68148/HTML/default/viewer.htm#etsug_varmax_details49.htm

eviews help
http://www.eviews.com/help/helpintro.html#page/content/coint-Johansen_Cointegration_Test.html
http://www.eviews.com/help/helpintro.html#page/content%2FVAR-Vector_Error_Correction_(VEC)_Models.html%23

PcGive has documentation similar to this (partially literal copy-pasted in tutorial)
Doornik, J. A., Hendry, D. F. and Nielsen, B. (1998), Inference in Cointegrating Models: UK M1 Revisited. Journal of Economic Surveys, 12: 533–572. doi:10.1111/1467-6419.00067
ungated copies of the working paper version and of PcGive documentation can be found by google

**Comment by josef-pkt** [comment]
The GSOC project was merged in #3246
