### ISSUE TITLE
roadmap 0.9

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3431]
(let's start another roadmap, even though we ignored and didn't follow the 0.7 or 0.8 roadmaps.)

- ...
- ...
- ...

- merge whatever comes up and is ready, 
- merge whatever ancient projects we manage to get ready

the biggies for 0.9:

- ???
- ???

(todo: rewrite roadmap)

**Comment by bashtage** [comment]
Some suggested tasks:

- [ ] Remove old compatibility code for unsupported versions of numpy, scipy, pandas
- [ ] Remove recarray support from datasets
- [ ] Cointegration testing
- [ ] pandas panel model port, or equivalent
- [ ] Other pandas stats that have been abondoned worth saving
- [ ] Refactor methods that use np.random directly to allow a user-provided RandomState

**Comment by mangecoeur** [comment]
FWIW, perhaps it might be worth moving to something like a date-driven, CI based release model? Given that its always hard to push out a release, and hard to decide what should be 'in' and what to wait for, perhaps it would make more sense to aim to push out a minor version e.g every 4 months (just a guess for the number) with emergency bug-fixes in between as necessary. That way instead of having to discuss/wait for things to be ready, just push out a release on the date with the latest commit that has all tests passing, anything not finished waits for the next release (?)

**Comment by bashtage** [comment]
I asked for this a while ago and there wasn't much support.  I think that this could be made much easier if some automation was added to the build:

* doctest run that actually checks for problems.  Run notebooks and check for errors, run datasets, and then parse log for unexpected WARNINGS or other errors.
* Automatically upload successful doctest build to statsmodels.org/dev
* Much shorter RC period and a model where release comes from master, rather than its own branch.  Basically after RC is called, not patches to master until release except those that address issues in the RC.  If this period was short (say 1 month).  Ready-but-non-RC-fixes could be staged and merged once the release is tagged.

Using a tag on master makes building wheels or conda easier IMO at some point after the release is tagged (could be days or weeks).  

This also means there would be no explicit branch maintenance, since the next release would either be a x.x.1 increment if small, or an x.1 is large changes.

**Comment by TomAugspurger** [comment]
+1 to all the points by @mangecoeur and @bashtage 

On the docs side, I'm partway through setting up doctr [here](https://drdoctr.github.io/doctr/). I'll revisit that in a couple weeks.

The only other thing I'd suggest is asking contributors to add a release note to `whatsnew/v0.x.x`. That's a bit more work on each PR, but much less work when it comes time to cut a release. Basically, I want to remove all the friction of cutting a release :)

**Comment by ChadFulton** [comment]
I suggest that the 0.9 release be based around the improved state space code, and so I suggest we target the release for as soon as we feel comfortable with (a) that code, and (b) the conditional compilation.

This is mainly just because I think that's a big enough change to merit a minor version bump, and also because since it's in master already, it means the release cycle will be much faster than last time :)

On the other hand, I don't track the non-tsa parts of statsmodels too much, so perhaps there are developments elsewhere that make this a bad idea.

**Comment by josef-pkt** [comment]
> On the other hand, I don't track the non-tsa parts of statsmodels too much, so perhaps there are developments elsewhere that make this a bad idea.

We would need more explicit "experimental" labels in some of the new code that is merged without having all the details figured out, but otherwise a release is not so much a question of code but about of release work.  
The new statespace framework is the only potentially "dangerous" code, for the rest it is mainly: good if we manage to get it in and get it clean, but if not, then we just take another version to get it merged or, if already merged, to get it reasonably stable. There are always many items on the wishlist for the next release, but given our lack of a fixed development plan, those are optional and do not need to hold up a release.  (We also had a "fixed" schedule when Skipper was doing the release work, it was essentially "make an annual release sometimes in summer".)

What I would like to avoid is the "limbo" status that we ended up in 0.7, 0.8 where development in master was partially on hold for some time because of an almost finished release which did not happen.

If changes spend less time in master before a release, it will increase the chance of refactoring bugs, but that mainly means that we would have to add quick-fix releases like other packages.

**Comment by bashtage** [comment]
Closing as out of date.
