### ISSUE TITLE
Forward Port from maintainence/0.8.x

### ISSUE THREAD

**Issue by TomAugspurger** [statsmodels/statsmodels#3455]
https://github.com/statsmodels/statsmodels/pulls?utf8=%E2%9C%93&q=is%3Apr%20label%3Aforwardport-0.8.0%20

Currently:

- [ ] DOC: Fix image build location  forwardport-0.8.0 #3454 by bashtage 
- [ ] DOC: Small doc fixes forwardport-0.8.0 #3453 by bashtage was merged an hour ago  
- [ ] CLN: Remote FutureWarning  forwardport-0.8.0 #3451 by bashtage was merged 10 hours ago

**Comment by bashtage** [comment]
Closed in #3459

**Comment by jbrockmendel** [comment]
@bashtage closeable (there’s a roundup of likely-closeable in #5155)
