### ISSUE TITLE
Internals TODO List

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3983]
This is a running TODO list for myself instead of opening a bunch of issues.

Code Cleanup
- [ ] Avoid 1-2 character variables names
- [ ] pep8 cleanup
- [ ] Avoid "import *"
- [ ] Avoid non-standard imports
- [ ] Indentation Fixup

Code Removal
- [ ] Remove code cannot possibly be run (e.g. `sandbox.km_class`)
- [ ] Remove commented-out code (e.g. `discrete_model.Weibull`)
- [ ] `if __name__ == "__main__"` blocks

Tests
- [ ] Mark smoke tests, get coverage statistics that exclude them
- [ ] Coverage for cython code
- [ ] Anything jpkt is hesitant to accept a PR --> consider suspect

Attribute Existence/Setting
- [ ] Avoid `__dict__` and `setattr`
- [ ] Validate `__init__` `*args, **kwargs` (ideally make them explicit)
- [ ] Instead of specifying `_data_attrs`, record them in the call to `handle_data`
- [ ] Some `Results` classes inherit `endog/exog`, not consistent

De-Duplication
- [ ] `_get_robustcov_results` in models and in `base.covtype`
- [ ] Lots of stuff in sandbox
- [ ] `summary` vs `summary2`

Degrees of Freedom
- [ ] Avoid altering model `df_model` and `df_resid` attributes
- [ ] Check/formalize/standardize `# assumes const`
- [ ] Standardize `df_resid = nobs - (df_model + k_const)`
- [ ] Standardize `exog.shape[1]` vs `np.linalg.matrix_rank(exog)`
- [ ] aic/bic/... inconsistent definitions

Naming Conventions
- [ ] Unify `self.y` vs `self.endog`, `endog_lagged`, `y_lagged`, ...
- [ ] `arparams` vs `ar` vs `arpoly` vs `arcoefs` vs `params`

Unsorted
- [ ] deprecate `tsa.base.datetools`, get pandas or dateutil to extra cases

**Comment by jbrockmendel** [comment]
Never mind.
