### ISSUE TITLE
SUMM: Possibly Unnecessary Files

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5137]
Non-Python Files
- [ ] sandbox/tests/test_bspline.py.txt
- [x] statsmodels/LICENSE.txt (#4973, #4931)
- [ ] statsmodels/datasets/README.txt (overlap with tools/dataset_rst.py, sandbox/dataset_notes.rst)
- [ ] sandbox/mlogitmath.lyx
- [ ] sandbox/tools/TODO.txt
- [ ] sandbox/tsa/notes_organize.txt
- [ ] sandbox/regression/notes_runml.txt
- [ ] sandbox/mcevaluate/mcresuts_arma1.txt
- [ ] sandbox/stats/notes_fdr.txt
- [ ] readme_l1.txt (#4957)

Python files for which there appear to be either no use or strictly dominating alternatives
- [x] statsmodels/info.py (#4981)
- [x] statsmodels/examples/t_est_rlm.py (#5109, #5100)
- [x] statsmodels/sandbox/tests/model_results.py (#5070)
- [x] sandbox/examples/ex_kaplan_meier.py (#5071)
- [x] statsmodels/sandbox/tests/datamlw.py (#4941)
- [ ] statsmodels/sandbox/formula.py (#4940)
- [ ] statsmodels/tsa/mlemodel.py (#5139)
- [ ] statsmodels/tsa/descriptivestats.py
- [ ] sandbox/utils_old.py
- [ ] sandbox/mle.py ('''What's the origin of this file?  It is not ours")
- [ ] sandbox/bspline.py (imports `from models import _hbspline` which does not exist AFAIK)
- [ ] sandbox/regression/sympy_diff.py
- [ ] sandbox/regression/ols_anova_original.py
- [ ] sandbox/panel/sandwich_covariance.py
- [ ] nonparametric/smoothers_lowess_old.py (#5142)
- [ ] iolib/stata_summary_examples.py (#5061)
- [ ] iolib/tests/test_summary.py (#5064)
- [ ] iolib/tests/test_summary_old.py (#5064)
- [ ] emplike/koul_and_mc.py

Many files in tools/ may be relevant for the release process (if so I'm not sure if that is documented), so the following are a special type of tentative:
- [ ] tools/generate_formula_api.py (#5118)
- [ ] tools/code_maintenance.py
- [ ] tools/gh_api.py
- [ ] tools/github_stats.py
- [ ] tools/matplotlibrc.qt4
- [ ] tools/matplotlibrc.qt5
- [ ] tools/README.rst
- [ ] tools/update_web.py
- [ ] tools/binstar/
- [ ] tools/check_dirs.py
- [ ] tools/backport_pr.py

Docs
- [ ] GLMNotes.lyx, GLMNotes.pdf - last touched in 2012
- [ ] fix_longtable.py - last touched in 2012, grep shows not used elsewhere

Misc
- [ ] A bunch of duplicated files in statsmodels/datasets/
- [ ] resampling/
- [ ] interface/
- [ ] sandbox/stats/tests/

**Comment by josef-pkt** [comment]
`statsmodels\graphics\plot_grids.py`
has zero test coverage
I guess the module is outdated, and maybe obsolete, i.e. written a long time ago before pandas, matplotlib and seaborn supported more of this directly.
The `scatter_ellipse` function still works without problems.

**Comment by jbrockmendel** [comment]
- [ ] examples/tsa/lagpolynomial.py

**Comment by jbrockmendel** [comment]
Closing in favor of #5773
