### ISSUE TITLE
SUMM: Roundup of mangled, commented-out, docstringed-out tests

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5145]
From browsing Issues/PRs (not yet an actual sweep through the code #4966)

- [ ] nonparametric.tests.test_kernels.T_estCosine
- [ ] nonparametric.tests.test_kernelsCheckKernelMixin. t_est_smoothconf_data
- [ ] test_data.TestDates
- [x] test_data.T_estWaldAnovaOLSNoFormula
- [x] test_discrete.pvalues (#4983)
- [x] test_discrete.test_cov_params (#4983)
- [x] test_discrete.test_normalized_cov_params  (#4983)
- [x] test_discrete.test_jac  (#4983)
- [x] test_discrete.test_predict
- [x] test_discrete.test_predict_xb
- [ ] test_sarimax.test_bse_approx
- [x] test_glm_weights.test_basic (#4980)
- [x] test_glm_weights.test_compare_optimizers (#4980)
- [x] test_robustcov.test_hac_simple (#4980)
- [x] test_robustcov.test_fvalue (#4980)
- [x] test_robustcov. t_est_fvalue (#4980)
- [x] test_robustcov.test_f_value (#4980)
- [x] test_robustcov.test_confint (#4980)
- [x] test_generic_methods. T_estWaldAnovaOLSNoFormula (#4978)
- [ ] test_dynamic_factor.test_mle (#5115)
- [x] examples.t_est_rlm (#5100)
- [ ] test_diagnostic.notyet_atst (#5085)
- [ ] test_qsturng.test_all_to_tbl (#5084)
- [x] test_tools.test_arraylike2d (#4862, #4324)
- [x] test_tools.test_arraylike1d (#4862, #4324)
- [x] test_tools.test_arraylike2d_drop (#4862, #4324)
- [x] test_tools.test_arraylike1d_drop (#4862, #4324)
- [x] test_tools.test_array2d (#4862, #4324)
- [x] test_tools.test_array1d (#4862, #4324)
- [x] test_tools.test_array2d_drop (#4862, #4324)
- [x] test_generic_methods.T_estWaldAnovaOLSNoFormula (#4343)
- [ ] test_gmm `est_other` --> `test_other`
- [ ] test_gmm test_other commented out assertion
- [ ] test_gmm test_basic commented-out assertion
- [ ] test_gmm test_bse_other commented-out assertions
- [ ] test_gmm test_hypothesis commented-out assertions
- [ ] test_gmm test_iv2sls_r commented-out assertion
- [ ] `test_tools` tests named `test_13`, `test_41`, ... these presumably refer to GH issues, need meaningful names
- [ ] `test_rootfinding.test_brentq_expanding` commented-out assertions 
- [ ] `test_numdiff` `test_hess` commented-out assertions.
- [ ] `test_data` `test_patsy_577` should have meaningful name
- [ ] `test_qsturng` `test_more_exotic_stuff`commented out, needs better name
- [ ] `test_qsturng` `test_all_to_tbl` "#remove from testsuite"
- [ ] `test_weightstats.TestZTest.test` split into well-scoped tests, possibly parametrize
- [ ] `test_weightstats` `CheckWeightstats1dMixin` commented-out `def` with commented-out assertion
- [ ] `test_weightstats.CheckWeightstats1dMixin.test_basic` commented-out assertion
- [ ] `test_weightstats` `test_weightstats_1-3` commented-out assertions/prints

Smoke tests that should be marked, separated, etc
- [x] test_penalized.test_smoke
- [x] test_robustcov.test_smoke (#4980)

**Comment by jbrockmendel** [comment]
ditto t_est_smoothconf_data

**Comment by jbrockmendel** [comment]
- [ ] `test_tools` tests named `test_13`, `test_41`, ... these presumably refer to GH issues, need meaningful names
- [ ] `test_rootfinding.test_brentq_expanding` commented-out assertions 
- [ ] `test_numdiff` `test_hess` commented-out assertions.
- [ ] `test_data` `test_patsy_577` should have meaningful name
- [ ] `test_qsturng` `test_more_exotic_stuff`commented out, needs better name
- [ ] `test_qsturng` `test_all_to_tbl` "#remove from testsuite"
- [ ] `test_weightstats.TestZTest.test` split into well-scoped tests, possibly parametrize
- [ ] `test_weightstats` `CheckWeightstats1dMixin` commented-out `def` with commented-out assertion
- [ ] `test_weightstats.CheckWeightstats1dMixin.test_basic` commented-out assertion
- [ ] `test_weightstats` `test_weightstats_1-3` commented-out assertions/prints

**Comment by jbrockmendel** [comment]
Closing in favor of #5773.
