### ISSUE TITLE
SUMM: PRs that have gotten "LGTM"

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5147]
(or approximate equivalent)

- [x] #5058 (bashtage) BUG: Don't use mutable default values --> OKed by josef
- [x] #4871 (bashtage) BLD: Refactor Setup --> OKed by josef (pending rebase)
- [x] #4949 (bashtage) BUG: Set default lags for acf/pacf plots --> OKed by josef
- [x] #4963 (bashtage) BUG: Remove change of global pickle method --> OKed by jbrockmendel
- [x] #4990 (jbrockmendel) [MAINT/CLN] remove `__main__` section explicitly marked as scratch work --> OKed by bashtage
- [x] #5090 (thequackdaddy) MAINT: Chrome doesn't like having a secure link with an unsecure image --> OKed by bashtage, jbrockmendel
- [x] #5162 (jbrockmendel) TST: Fix incorrect test closes #4325 --> OKed by bashtage
- [x] #5184 TST: parametrize tests in test_lme --> OKed by kshedden
- [x] #5248 DOC: Revert incorrect docstring change [skip ci] --> OKed by jbrockmendel
- [x] #5152 (fourpoints) REF: Use iterative cumsum --> OKed by josef
- [x] #5156 (jbrockmendel) TST: Remove __main__ sections in tests --> OKed by bashtage
- [x] #5148 (bashtage) REF/TST: add seed to hdrboxplot, Use random order in pytest --> OKed by josef
- [x] <s>#4973 (jbrockmendel) update license year 2018, remove duplicate license file --> OKed by bashtage</s> (superseded by #5195)
- [x] <s>#5028 (jbrockmendel) BUG: Fix return of ValueError instead of Raise --> OKed by bashtage</s> superseded by #5203
- [x] #5132 (jbrockmendel) MAINT/TST: Fix/Silence DeprecationWarnings --> OKed by bashtage
- [x] #5003 (jbrockmendel) MAINT: fix invalid exception messages --> OKed by bashtage
- [x] #5029 (jbrockmendel) MAINT: strict linting for sm.stats files _close_ to already passing --> OKed by bashtage
- [x] #4977 (jbrockmendel) [BUG/MAINT] Fix NameErrors caused by missing kwargs --> OKed by bashtage
- [x] #5005 (jbrockmendel) [MAINT] remove unused imports in examples+tools --> OKed by bashtage
- [x] #4989 (jbrockmendel) [MAINT/CLN] Remove code made unusable due to license issue --> OKed by bashtage
- [x] #5021 (jbrockmendel) MAINT: fix typo duplicated References in docstring --> OKed by bashtage
- [x] #4865 (amirmasoudabdol) Update contingency_tables.rst --> OKed by josef, pending rebase
- [x] #4933 (MaxGhenis) Remove unused patsy import in quantile_regression.ipynb --> OKed by bashtage, jbrockmendel
- [x] #5157 (jbrockmendel) TST: consolidate version checks, remove outdated --> OKed by bashtage
- [x] #5168 (jbrockmendel) MAINT: Consolidate "Remove Defunct X" PRs --> OKed by bashtage
- [x] #5170 (jbrockmendel) DEPR: Remove items deprecated in previous versions
- [x] #5223 MAINT: fully lint compat --> OKed by bashtage
- [x] #5222 MAINT: fully lint formula --> OKed by bashtage
- [x] #5218 MAINT: Move misplaced genmod results files --> OKed by bashtage
- [x] #5221 MAINT: remove never-needed callable and never-used compat functions --> OKed by bashtage
- [ ] #5233 DOC: Completed documentation of elements in possible dataFrames from anova_lm --> OKed by bashtage
- [x] #5263 BLD: Only unshallow when required --> OKed by jbrockmendel

@josef-pkt you mentioned a) that a SUMM issue would be the appropriate place for this and b) that going through PRs to see which is ready is burdensome.  Helping triage.

**Comment by jbrockmendel** [comment]
#4933 (MaxGhenis) Remove unused patsy import in quantile_regression.ipynb --> OKed by bashtage, jbrockmendel

**Comment by jbrockmendel** [comment]
There are a handful more that got less-explicit OKs that I’ll draw attention to if/when these get whittled down.  A lot of the older PRs have rotted past the point of obviousness.

**Comment by josef-pkt** [comment]
Thanks, that's useful

I will try to whittle.
(scheduled for today: birthday party of 10 year old, and ordering 40,000 CAD worth of windows, literal not the computer version)

**Comment by jbrockmendel** [comment]
Knocked a couple out, plus a few not on the list.  A good day.  If I wore a hat, I'd doff it to you.

**Comment by jbrockmendel** [comment]
- [ ] #5152 (fourpoints) REF: Use iterative cumsum --> OKed by josef

**Comment by jbrockmendel** [comment]
Next up: collecting PRs that had requested edits that appear to have been addressed (and are de-facto green).

- [ ] #4925 (bashtage) CLN: Enforce E721, use isinstance

**Comment by jbrockmendel** [comment]
@josef-pkt I'm in the process of closing as many CLN PRs as I can stomach; leaving ones on the list above open.  Any additional whittling will be appreciated.

**Comment by jbrockmendel** [comment]
@josef-pkt ping

**Comment by jbrockmendel** [comment]
Alright, he’s on a roll.  5162 might be a good next step

**Comment by jbrockmendel** [comment]
- [ ] #5223 MAINT: fully lint compat --> OKed by bashtage
- [ ] #5222 MAINT: fully lint formula --> OKed by bashtage
- [ ] #5218 MAINT: Move misplaced genmod results files --> OKed by bashtage
- [ ] #5221 MAINT: remove never-needed callable and never-used compat functions --> OKed by bashtage

@josef-pkt got a handful more pre-approved PRs in addition to the original batch.

**Comment by jbrockmendel** [comment]
- [ ] #5233 DOC: Completed documentation of elements in possible dataFrames from anova_lm --> OKed by bashtage
- [ ] #5184 TST: parametrize tests in test_lme --> OKed by kshedden

**Comment by jbrockmendel** [comment]
- [ ] #5263 BLD: Only unshallow when required --> OKed by jbrockmendel
- [ ] #5248 DOC: Revert incorrect docstring change [skip ci] --> OKed by jbrockmendel

**Comment by jbrockmendel** [comment]
@kshedden @ChadFulton you two did a bang-up job yesterday in closing.  I've consolidated the list of already-approved PRs above just waiting for the green button to be hit.  Be the change you want to see in the repo.

**Comment by jbrockmendel** [comment]
Got all of them, closing.
