### ISSUE TITLE
SUMM: CI Improvements

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5154]
A few CI improvements got merged recently.  Props to all involved.

- [ ] GH tag for CI
- [x] Empower a junior maintainer with comparative advantage in CI.
- [x] set codecov settings to allow margin of error (comment from @rgommers) (closed by #5635)
- [ ]  use only one of codecov/coveralls?  both seem to give apparently random failures, might cut down on those.
- [ ] config for codacy to avoid false-positives
- [x] #5144 Use CircleCI to take some of the pressure off Travis
- [x] #5110 TST: randomize order of tests (closed by #5148)
- [ ] #5082 TST: Codecov False-Positives caused by Noise in mixed_linear_model tests?
- [x] #4779 MAINT: travis explicitly specify MKL or OpenBLAS (closed by #4823)
- [x] #2069 run unit tests on Mac OSX

**Comment by rgommers** [comment]
there is a build tag: https://github.com/statsmodels/statsmodels/labels/build

**Comment by jbrockmendel** [comment]
I’m retroactively persuasive.

**Comment by bashtage** [comment]
#4779 is complete and can be closed.

**Comment by bashtage** [comment]
xref #5186

**Comment by bashtage** [comment]
Coveralls seems to tolerate small decreases now.  Codecov still complains.

**Comment by jbrockmendel** [comment]
Closing in favor of #5632.
