### ISSUE TITLE
SUMM: Closeable/Duplicate Issues

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5155]
Some of these may have fallen through the cracks.

Explicitly Closed
- [x] #883 formula.api cleanup remove classes (closed by #5146)
- [x] #3455 Forward Port from maintainence/0.8.x (closed by #3459)

Possible Duplicate
- [ ] #2784 / #660 SUMM/REF: grouputils
- [x] #613 / #695 / #703 / #829 pylint cleanup (josef: "I would like to get to this ASAP.")

Possibly Stale/Irrelevant
- [x] #1322 Including Examples
- [ ] #1280 Cleanup: Remove branches from main repo

Possibly Relevant, but not clearly actionable
- [x] #3076 release 0.9

GH Labels - some of these may be defunct, others may benefit from clearer names
- [x] backport-0.5.1
- [x] backport-0.6.1
- [x] backport-0.8.0
- [x] backport-0.9.0 (0.8.1 still has an open Issue, so not included in this list)
- [x] type-invalid (not clear what "invalid" means in this context)
- [x] type-bug-wrong (has 1 open issue, but not clear what the difference is vs type-bug)
- [x] topic_covtype (rename topic-covtype for consistency?)
- [x] prio_elev (rename prio-elev for consistency?)
- [x] not-master
- [ ] needs-release-note (this one is pretty clear, just appears unused)
- [x] forwardport-0.8.0

**Comment by josef-pkt** [comment]
about GH labels: 
we don't remove labels because we want to keep them as part of history, i.e. old backports
I renamed the two underline spelling, and added a short description got bug-wrong and type-invalid

`bug-wrong` are serious bugs that should be quickly fixed
`invalid` is a generic indication that an issue can be ignored, even if the title sounds serious/severe.

(written 6 days ago but lost among many open tabs)

**Comment by jbrockmendel** [comment]
Thanks for clarifying on the invalid-wrong bit, makes sense.

**Comment by bashtage** [comment]
The ones that are solvable have been removed.  The rest appear valid.
