### ISSUE TITLE
Issue Labels

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5708]
Labels to consider implementing:
- [ ] CI
- [ ] EX (Example)
- [ ] SUMM
- [ ] Something for "consider implementing FooBar model"
- [ ] Segfaults (severe, un-recoverable bugs)
- [ ] Internal consistency (#3629, #3689, #4030, #4522, #4742...)
- [ ] Overflows/Numeric
- [ ] Failing Test (#4850)/Inconsistency on Windows (#4737)/...
- [ ] Comment/Question (#4956, #4961)
- [ ] Regression (might want a more specific name for this context; e.g. #5333)

@bashtage collecting these here instead of pinging you a zillion times.  I've looked through about half the Issues so far, will post below if I identify more

- [ ] #5406: RLS
- [ ] #5330: RLS
- [ ] #3982: RLS -- not sure about this label
- [ ] #3075: RLS
- [ ] #3076: RLS
- [ ] #3431: RLS
- [ ] #4507: RLS
- [ ] #4573: RLS
- [ ] #5290: RLS
- [ ] #5371: BLD
- [ ] #5035: BLD
- [ ] #4407: BLD
- [ ] #4160: BLD
- [ ] #4150: BLD
- [ ] #3596: BLD
- [ ] #3373: BLD
- [ ] #4657: BLD
- [ ] #5326: PERF
- [ ] #5199: PERF
- [ ] #4752: PERF
- [ ] #3082: PERF (closeable?)
- [ ] #3237: PERF
- [ ] #3399: PERF
- [ ] #3542: PERF
- [ ] #3609: PERF
- [ ] #4187: PERF
- [ ] #4239: PERF  --> already has tag, but I think duplicate of something else above
- [ ] #4546: PERF
- [ ] #4608: PERF
- [ ] #5344: PERF
- [ ] #5688: BUG
- [ ] #4618: BUG
- [ ] #4544: BUG, pandas-compat
- [ ] #4541: BUG, pandas-compat
- [ ] #4332: BUG (not sure about label, CLN doesnt seem right)
- [ ] #5134: CLN
- [ ] #5126: CLN
- [ ] #5125: CLN
- [ ] #5111: CLN
- [ ] #5062: CLN
- [ ] #5023: CLN
- [ ] #5019: CLN
- [ ] #4994: CLN
- [ ] #4422: CLN
- [ ] #4419: CLN
- [ ] #4062: CLN
- [ ] #4110: CLN
- [ ] #5025: CLN
- [ ] #4220: CLN, REF, ENH
- [ ] #5225: EX
- [ ] #5037: EX
- [ ] #4935: TST
- [ ] #3078: TST, ENH
- [ ] #5082: TST
- [ ] #4966: TST
- [ ] #4549: pandas-compat (maybe specific for wrapping?)
- [ ] #4544: pandas-compat (maybe specific for Categorical?)
- [ ] #4541: pandas-compat (maybe specific for wrapping?)
- [ ] #4894: pandas-compat
- [ ] #3306: DOC
- [ ] #4085: DOC
- [ ] #4199: DOC
- [ ] #3433: DEPR
- [ ] #3462: DEPR
- [ ] #5092: DEPR
- [ ] #4964: DEPR/DES
- [ ] #5019: MAINT
- [ ] #5472: py27-specific

Closeable? (see also #5155):
- [ ] #3555
- [ ] #3214
- [ ] #3780
- [ ] #4466

**Comment by jbrockmendel** [comment]
- [ ] #4204 Closable

**Comment by jbrockmendel** [comment]
Just made a pass through the older half of issues:


A motivated maintainer can accomplish immediately:
- [ ] #1280: Remove branches from main repo


Missing Labels:
- [ ] #89: PERF (likely closable)
- [ ] #73: Naming Conventions/Internal Consistency
- [ ] #157: Naming Conventions/Internal Consistency
- [ ] #296: PERF
- [ ] #375: pandas-wrapping
- [ ] #487: Naming Conventions/Internal Consistency
- [ ] #583: NumericalPrecision
- [ ] #814: pandas-wrapping
- [ ] #1162: Naming Conventions/Internal Consistency
- [ ] #1181: Naming Conventions/Internal Consistency
- [ ] #1335: Naming Conventions/Internal Consistency
- [ ] 1342: pandas-categorical
- [ ] #1376: TST
- [ ] #1663: PERF
- [ ] #1664: Naming Conventions/Internal Consistency
- [ ] #1848: PERF
- [ ] #2113: PERF
- [ ] #2207: Naming Conventions/Internal Consistency
- [ ] #2262: NumericalPrecision
- [ ] #2314: Naming Conventions/Internal Consistency
- [ ] #2326: EX
- [ ] #2270: pandas-wrapping
- [ ] #2360: PERF
- [ ] #2447: PERF
- [ ] #2484: Naming Conventions/Internal Consistency
- [ ] #2585: PERF
- [ ] #2585: pandas-compat
- [ ] #2914: PERF

Closeable?
- [ ] #475: genfromdta
- [ ] #476: genfromdta
- [ ] #469
- [ ] #695: pylint
- [ ] #780
- [ ] #829
- [ ] #833: closed by #5146
- [ ] #903: closed by #5592
- [ ] #886
- [ ] #1063
- [ ] #1237
- [ ] #2463
- [ ] #2593: closed by #5042
- [ ] #1893
- [ ] #1086
- [ ] #1324: str/bytes
- [ ] #1290: unicode
- [ ] #1746: unicode
- [ ] #1892
- [ ] #2341

**Comment by bashtage** [comment]
I closed what I felt comfortable with.

**Comment by jbrockmendel** [comment]
- [ ] #306

**Comment by jbrockmendel** [comment]
- [ ] #437 - close as duplicate of #5441, which has the FAQ label
- [ ] #1270 - close as duplicate of #5441, which has the FAQ label
