### ISSUE TITLE
SUMM: Roundup of sandbox exposure, unused files, redundant code, ...

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5773]
Collecting these in one place to avoid Issue proliferation; will update as appropriate.

Sandbox
---------
Parts of sandbox that are imported from non-sandbox (cc @ChadFulton if you were wondering how much of the code implicitly relies on sandbox):
- [ ] `sandbox.tsa.fftarma.Armafft`
    - [ ] In several of the places this is imported it is only for the `generate_sample` method, which is defined on the non-sandbox parent class `ArmaProcess`.  Use `ArmaProcess` directly.
   - [ ] The only remaining place where `fftarma` is imported is in `test_arima_process`, where it has two tests for `Armafft`.  These could be moved to a test file in sandbox specific to `fftarma`.
- [ ] `sandbox.stats.diagnostic` almost all of `stats.diagnostic` comes from here.
  - [ ] The _good_ news is that aside from this pass-through, the only direct import from `sandbox.diagnostics` is in examples/ex_arch_canada.py for `acorr_lm`.
- [ ] `statsmodels.sandbox.regression.predstd` is imported in numerous test and example files to get `wls_prediction_std` (looks like 10 imports total, 13 if we count notebook files)
    - Also in `stats.outliers_influence` and `graphics.regressionplots` (i.e. user-facing code)
- [ ] `sandbox.regression.penalized` is imported in several test files for `TheilGLS`.  This includes a `test_theil` file in `regression.tests` that sends mixed messages as to the status of this file.
- [ ] `sandbox.tsa.garch` is imported in statsmodels/examples/tsa/ex_arma.py for its `Arma` class
- [ ] `sandbox.nonparametric.kernels` is imported into 2 files in `nonparametric` and 3 files in `nonparametric.tests`.
   - `sandbox.nonparametric` files are imported into 6 examples/ files
- [ ] `sandbox.distributions.mv_normal` is imported into `distributions.mixture_rvs` and `distributions.tests.test_mixture`
  - `sandbox.distributions.sppatch` is imported into examples/ex_generic_mle_tdist.py
- [ ] `stats.multicomp` imports `tukeyhsd` and `MultiComparison` from `sandbox.stats.multicomp` (there is only one function defined directly in `stats.multicomp`)
  - [ ] `sandbox.stats.multicomp` is imported into `stats.contrast` for `contrast_allpairs` (which is also duplicated in `sandbox.stats.contrast_tools`)
  - [ ] `sandbox.stats.multicomp.get_tukeyQcrit` is imported into `stats.tests.test_qsturng`
- [ ] `sandbox.tools.cross_val.LeaveOneOut` is imported into `stats.outlier_influence`.  This class is also duplicated in `nonparametric._kernel_base`
- [ ] `sandbox.stats.runs` provides `Runs`, `runstest_1samp`, and `runstest_2samp` directly to `stats.api`.
  - [ ] The same three are imported in `stats.tests.test_nonparametric`, along with `sandbox.stats.runs.mcnemar`
- [ ] `statsmodels.sandbox.panel.random_panel` is imported for `PanelSample` in `regression.tests.test_theil`

De Facto Sandbox
------------------
Non-Sandbox code that belongs in sandbox or dustbin:
- [ ] `nonparametric.smoothers_lowess_old`
- [ ] `tsa.descriptivestats`
- [ ] `tsa.mlemodel`
- [ ] `tsa.arma_mle`
- [ ] `tsa.varma_process`
- [ ] `miscmodels.try_mlecov`
- [ ] `iolib.stata_summary_examples`
- [ ] `iolib.tests.test_summary_old`

Chopping Block
----------------
Sandbox files that are especially unlikely to be useful:
- [ ] mle.py - starts with "What's the origin of this file? It is not ours"
- [ ] mlogitpath.lyx - no idea why we would need a lyx file
- [ ] formula - supplanted by patsy (#5692)
- [ ] contrast_old, tools_old - only used by formula (#5692)
- [ ] dataset_notes.rst - likely redundant with README in `datasets` directory
- [ ] tsa/notes_organize.txt still refers to scikits.statsmodels
- [ ] `sandbox.regression.ols_anova_original` - OK I haven't looked it this closely, but it looks like it was superceded and then never removed.

Duplication
-----------
Copy/Pasted code that should be imported instead:
- [ ] `sandbox.tsa.garch` copies all of `LikelihoodModel` (#4422)
- [ ] `LeaveOneOut` class in both `sandbox.tools.cross_val` and `nonparametric._kernel_base`

Disabled Code
---------------
Commenting out code is a way of temporarily disabling it that tends to become permanent and make things more difficult for subsequent readers.
- [ ] `tsa.interp.denton.denton`
- [ ] `discrete.discrete_model.Weibull`

Namespace Issues
-------------------
- [ ] `tools._testing` and `tools.testing`: either choose just one or make a clear distinction between what belongs where (#4876)
- [ ] examples vs statsmodels/examples vs sandbox/examples, sandbox/distribution/examples, ... could use clarification

Unsorted
---------
- [ ] `miscmodels.tests.test_generic_mle` contains tests for GenericLikelihoodModel, not anything in `miscmodels`  (#5763).  If, as I suspect, `miscmodels` serves primarily as tests/examples for `GenericLikelihoodModel`, that should be made explicit and implement systematically.
- [ ] Many files like e.g. `sandbox.regression.example_kernridge` that may belong in e.g. andbox/regression/examples/?

**Comment by jbrockmendel** [comment]
Moving from #5145 

Mangled, Commented-Out, or Otherwise Disabled Tests
--------------------------------------------------------
With pytest.mark.skip or pytest.mark.xfail we can easily find things that need attention.  Other methods of "temporarily" skipping a test get lost easily.  See also #5768.

- [ ] nonparametric.tests.test_kernels.T_estCosine
- [ ] nonparametric.tests.test_kernelsCheckKernelMixin. t_est_smoothconf_data
- [ ] test_data.TestDates
- [x] test_data.T_estWaldAnovaOLSNoFormula
- [x] test_discrete.pvalues (#4983)
- [x] test_discrete.test_cov_params (#4983)
- [x] test_discrete.test_normalized_cov_params  (#4983)
- [x] test_discrete.test_jac  (#4983)
- [x] test_discrete.test_predict
- [x] test_discrete.test_predict_xb
- [ ] test_sarimax.test_bse_approx
- [x] test_glm_weights.test_basic (#4980)
- [x] test_glm_weights.test_compare_optimizers (#4980)
- [x] test_robustcov.test_hac_simple (#4980)
- [x] test_robustcov.test_fvalue (#4980)
- [x] test_robustcov. t_est_fvalue (#4980)
- [x] test_robustcov.test_f_value (#4980)
- [x] test_robustcov.test_confint (#4980)
- [x] test_generic_methods. T_estWaldAnovaOLSNoFormula (#4978)
- [ ] test_dynamic_factor.test_mle (#5115)
- [x] examples.t_est_rlm (#5100)
- [ ] test_diagnostic.notyet_atst (#5085)
- [ ] test_qsturng.test_all_to_tbl (#5084)
- [x] test_tools.test_arraylike2d (#4862, #4324)
- [x] test_tools.test_arraylike1d (#4862, #4324)
- [x] test_tools.test_arraylike2d_drop (#4862, #4324)
- [x] test_tools.test_arraylike1d_drop (#4862, #4324)
- [x] test_tools.test_array2d (#4862, #4324)
- [x] test_tools.test_array1d (#4862, #4324)
- [x] test_tools.test_array2d_drop (#4862, #4324)
- [x] test_generic_methods.T_estWaldAnovaOLSNoFormula (#4343)
- [ ] test_gmm `est_other` --> `test_other`
- [ ] test_gmm test_other commented out assertion
- [ ] test_gmm test_basic commented-out assertion
- [ ] test_gmm test_bse_other commented-out assertions
- [ ] test_gmm test_hypothesis commented-out assertions
- [ ] test_gmm test_iv2sls_r commented-out assertion
- [ ] `test_tools` tests named `test_13`, `test_41`, ... these presumably refer to GH issues, need meaningful names
- [ ] `test_rootfinding.test_brentq_expanding` commented-out assertions 
- [ ] `test_numdiff` `test_hess` commented-out assertions.
- [ ] `test_data` `test_patsy_577` should have meaningful name
- [ ] `test_qsturng` `test_more_exotic_stuff`commented out, needs better name
- [ ] `test_qsturng` `test_all_to_tbl` "#remove from testsuite"
- [ ] `test_weightstats.TestZTest.test` split into well-scoped tests, possibly parametrize
- [ ] `test_weightstats` `CheckWeightstats1dMixin` commented-out `def` with commented-out assertion
- [ ] `test_weightstats.CheckWeightstats1dMixin.test_basic` commented-out assertion
- [ ] `test_weightstats` `test_weightstats_1-3` commented-out assertions/prints

Smoke tests that should be marked, separated, etc
- [x] test_penalized.test_smoke
- [x] test_robustcov.test_smoke (#4980)

**Comment by jbrockmendel** [comment]
Unused/Unmaintained `__main__` Sections
-------------------------------------------
Moved from #5128 

https://github.com/statsmodels/statsmodels/pull/3515#issuecomment-282926964

Searching 1493 files for "`__main__`" (regex, case sensitive)
- [x] setup.py
- [x] statsmodels/base/tests/test_data.py
- [x] statsmodels/base/tests/test_shrink_pickle.py
- [x] statsmodels/base/wrapper.py
- [x] statsmodels/compat/tests/test_itercompat.py
- [x] statsmodels/discrete/tests/test_discrete.py
- [x] statsmodels/discrete/tests/test_sandwich_cov.py
- [x] statsmodels/distributions/edgeworth.py
- [ ] statsmodels/distributions/empirical_distribution.py
- [ ] statsmodels/distributions/mixture_rvs.py
- [x] statsmodels/distributions/tests/test_discrete.py
- [x] statsmodels/distributions/tests/test_edgeworth.py
- [x] statsmodels/distributions/tests/test_mixture.py
- [x] statsmodels/duration/tests/test_phreg.py
- [ ] statsmodels/examples/ex_kernel_regression2.py
- [ ] statsmodels/examples/ex_kernel_regression3.py
- [ ] statsmodels/examples/ex_kernel_regression_censored2.py
- [ ] statsmodels/examples/ex_kernel_regression_dgp.py
- [ ] statsmodels/examples/ex_kernel_regression_sigtest.py
- [ ] statsmodels/examples/ex_kernel_semilinear_dgp.py
- [ ] statsmodels/examples/ex_kernel_singleindex_dgp.py
- [ ] statsmodels/examples/ex_kernel_test_functional.py
- [ ] statsmodels/examples/ex_kernel_test_functional_li_wang.py
- [ ] statsmodels/examples/ex_multivar_kde.py
- [ ] statsmodels/examples/ex_outliers_influence.py
- [ ] statsmodels/examples/ex_pairwise.py
- [ ] statsmodels/examples/ex_rootfinding.py
- [ ] statsmodels/examples/l1_demo/demo.py
- [ ] statsmodels/examples/try_fit_constrained.py
- [ ] statsmodels/examples/try_power2.py
- [ ] statsmodels/genmod/_tweedie_compound_poisson.py
- [x] statsmodels/genmod/families/tests/test_link.py
- [ ] statsmodels/genmod/generalized_linear_model.py
- [ ] statsmodels/genmod/tests/gee_categorical_simulation_check.py
- [ ] statsmodels/genmod/tests/gee_gaussian_simulation_check.py
- [ ] statsmodels/genmod/tests/gee_poisson_simulation_check.py
- [ ] statsmodels/genmod/tests/results/gee_generate_tests.py
- [x] statsmodels/genmod/tests/test_glm.py
- [x] statsmodels/graphics/tests/test_mosaicplot.py
- [x] statsmodels/graphics/tests/test_regressionplots.py
- [x] statsmodels/imputation/tests/test_mice.py
- [x] statsmodels/iolib/foreign.py
- [x] statsmodels/iolib/summary.py
- [x] statsmodels/iolib/tests/test_foreign.py
- [ ] statsmodels/iolib/tests/test_summary.py
- [ ] statsmodels/miscmodels/nonlinls.py
- [ ] statsmodels/miscmodels/try_mlecov.py
- [ ] statsmodels/nonparametric/kde.py
- [x] statsmodels/nonparametric/tests/test_bandwidths.py
- [x] statsmodels/nonparametric/tests/test_kde.py
- [x] statsmodels/nonparametric/tests/test_kernel_density.py
- [x] statsmodels/nonparametric/tests/test_kernel_regression.py
- [x] statsmodels/nonparametric/tests/test_kernels.py
- [x] statsmodels/nonparametric/tests/test_lowess.py
- [x] statsmodels/regression/linear_model.py
- [x] statsmodels/regression/tests/test_glsar_gretl.py
- [x] statsmodels/regression/tests/test_glsar_stata.py
- [ ] statsmodels/robust/robust_linear_model.py
- [ ] statsmodels/stats/_adnorm.py
- [ ] statsmodels/stats/anova.py
- [ ] statsmodels/stats/descriptivestats.py
- [x] statsmodels/stats/libqsturng/tests/test_qsturng.py
- [ ] statsmodels/stats/tabledist.py
- [x] statsmodels/stats/tests/test_anova.py
- [x] statsmodels/stats/tests/test_diagnostic.py
- [x] statsmodels/stats/tests/test_groups_sw.py
- [x] statsmodels/stats/tests/test_moment_helpers.py
- [x] statsmodels/stats/tests/test_power.py
- [x] statsmodels/stats/tests/test_proportion.py
- [x] statsmodels/stats/tests/test_sandwich.py
- [x] statsmodels/stats/tests/test_statstools.py
- [x] statsmodels/stats/tests/test_tost.py
- [x] statsmodels/tools/catadd.py
- [x] statsmodels/tools/dump2module.py
- [x] statsmodels/tools/grouputils.py
- [x] statsmodels/tools/numdiff.py
- [ ] statsmodels/tools/print_version.py
- [x] statsmodels/tools/tests/test_catadd.py
- [x] statsmodels/tools/tests/test_eval_measures.py
- [ ] statsmodels/tools/tests/test_numdiff.py
- [ ] statsmodels/tsa/ar_model.py
- [ ] statsmodels/tsa/arima_model.py
- [ ] statsmodels/tsa/base/tsa_model.py
- [ ] statsmodels/tsa/coint_tables.py
- [ ] statsmodels/tsa/filters/cf_filter.py
- [x] statsmodels/tsa/filters/tests/test_filters.py
- [ ] statsmodels/tsa/interp/denton.py
- [x] statsmodels/tsa/interp/tests/test_denton.py
- [x] statsmodels/tsa/kalmanf/kalmanfilter.py
- [ ] statsmodels/tsa/seasonal.py
- [x] statsmodels/tsa/tests/test_tsa_tools.py
- [ ] statsmodels/tsa/varma_process.py
- [ ] statsmodels/tsa/vector_ar/dynamic.py
- [ ] statsmodels/tsa/vector_ar/var_model.py

Some of these are in test files and are harmless-albeit-annoying.

**Comment by josef-pkt** [comment]
one comment to a group of `__main__` issues as in `statsmodels/examples/ex_kernel_regression_dgp.py`

Those are/were required (at least on Windows) for multiprocessing.
I don't remember the details nor whether it would be really necessary in each case or whether the same pattern was used "just in case" if there is multiprocessing.
