### ISSUE TITLE
RLS: Release v0.12.2

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#7251]
We have a couple of bug fixes in now that probably merit releasing a v0.12.2. Thanks to @bashtage for already merging a bunch of the backports into maintenance/v0.12.x in #7222. This means that I think the list of PRs to be backported now is only:

- [x] #7225 
- [x] #7229 
- [x] #7230
- [x] #7239
- [x] #7240
- [x] #7249
- [x] #7250
- [x] #7270 merged in master
- [x] #7259 bug lm test
- [x] #7228 rebased, merged
- [x] #7279  trivial change, merged in master
- [x] #7281 another bugfix with small change, merged in master
- [x] #7286 probit, cauchy link improvement, backwards compatible version, needs another look before merging

## Not backported

 - [ ] #7064 bug fix
 - [ ]  #7042 performance, no unit tests, maybe backport is not important enough 

I'd be happy to merge these into the maintenance branch and cut a release fairly quickly (e.g. this week) unless there are any concerns, @josef-pkt, @bashtage, @kshedden.

**Comment by josef-pkt** [comment]
Thanks @ChadFulton 

I will look in the next few days if there are some more that I would like to get into a bugfix release
The main undecided about how to backport would be fixing or speedup of probit link in GLM, from what I remember right now.

**Comment by ChadFulton** [comment]
Thanks @josef-pkt, I'll go ahead and backport the PRs I listed here, and then we can move ahead with the rest whenever that's convenient.

**Comment by bashtage** [comment]
Shall we put a deadline on backports?  Say Friday?

**Comment by ChadFulton** [comment]
> Shall we put a deadline on backports? Say Friday?

I agree, especially since we have a type bug wrong, so it would be good to get a release out for that.

**Comment by josef-pkt** [comment]
#7270 merged in master
#7259 bug lm test
#7228 rebased, can be merged when green

also with backport label:

#7064 bug fix
#7042 performance, no unit tests, maybe backport is not important enough

**Comment by bashtage** [comment]
#7291 has the backports.

**Comment by bashtage** [comment]
Release note night need one more pass.  Big blocker is that we aren't building docs.  I have doc building worked out using GH actions on other repos, so might try that.

**Comment by ChadFulton** [comment]
Thanks very much @bashtage, I dropped the ball on getting this out.

**Comment by ChadFulton** [comment]
> Big blocker is that we aren't building docs. I have doc building worked out using GH actions on other repos, so might try that.

It looks like Travis is still building the docs for us right now, or am I missing something?

**Comment by bashtage** [comment]
Does travis still run? It has seemed to hang on PRs.  But maybe I am
inpatient.

**Comment by ChadFulton** [comment]
> Does travis still run? It has seemed to hang on PRs.  But maybe I am
inpatient.

It is still running as of the last PR I merged (see e.g. https://travis-ci.org/github/statsmodels/statsmodels/builds/756956520?utm_source=github_status&utm_medium=notification), and the online documentation did update as expected from that PR. 

Maybe it is a quota issue, and sometimes we run out and it stops running?

**Comment by ChadFulton** [comment]
> Release note night need one more pass.

I am doing a pass of this and will merge an update soon.  Was there anything in particular you thought needed to be updated?

Otherwise, I guess we may as well release v0.12.2 once I update the release notes.

**Comment by bashtage** [comment]
Can we wait a day?  I need to run the wheel builder on the head of 0.12.x
to make sure the wheels pass.

**Comment by ChadFulton** [comment]
Yes, no problem!

**Comment by bashtage** [comment]
@ChadFulton If you want to take one more pass at the release notes you can do this and then tag 0.12.2.  The wheel building has all passed.

**Comment by ChadFulton** [comment]
v0.12.2 has been released.

**Comment by bashtage** [comment]
Wheels are up.

**Comment by ChadFulton** [comment]
> Wheels are up.

Thanks @bashtage!
