### ISSUE TITLE
SUMM: roadmap for 0.15 josef

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#8217]
(continuation of #7720 roadmap for 0.14)

- gmm for combining models, equations
   -  #8216
- ...
- ...

**Comment by josef-pkt** [comment]
list of smaller issues/pulls postponed to 0.15
https://github.com/statsmodels/statsmodels/issues/7720#issuecomment-1038444151

**Comment by josef-pkt** [comment]
There are still too many big topics, that need larger rounds

- robust
- penalization, penalized mixin, gam
- robust cov_type, CR3, HC in RLM, refactor/cleanup, ...
- multilink models
- a lot of stats
- ...
- ...

**Comment by josef-pkt** [comment]
look into #6537 irf and fevd for SVAR. I don't know how difficult this is

**Comment by josef-pkt** [comment]
I added new label "roadmap" so we/I can add roadmap issues by topic and not just by version
e.g. #8635 for copulas
I was recently thinking of many similar todo lists, but it's mostly in context of more specific bug/enh issues.

This will be similar to SUMM issues but more focused on check lists that we can work on and add check marks when merged or done. Details can be in other issues or in additional comments.
This worked well for my 0.14 roadmap.

**Comment by josef-pkt** [comment]
generic design issues that need decisions

- handling collinearity
- badly scaled, ill conditioned exog
- constraints
- handling rank reduce cov_params
- ???
- ...

aside: I looked a bit a pivoting qr in scipy.linalg.

**Comment by josef-pkt** [comment]
control function for endogenous regressors should not be too difficult #7689

to get started use continuous endogenous regressors.
theory for binary endogenous regressor (Logit, Probit) is messier, but it should work.
and later multinomial endogenous regressors

not clear yet from where to get the reference results for unit tests (Stata, R, Stata uses mainly bivariate normal for probit)

statsmodels.causal.control_function or statsmodels.causal.instrumental ?
do we put IV2SLS together with the control function approaches in nonlinear models?

models for GLM and discrete (Logit, Probit, Poisson)

one undecided question: How generic should this be? How many individual, case specific models?
e.g Stata has function to allow any type of endogenous regressor combinations. 
different models for different endogenous regressor types, continuous, binary, multinomial/ordered

simplest generic case similar to IV2SLS with OLS in 1st stage and whatever outcome model with control functions (functions of first stage residuals) in second stage, and GMM for cov_params.

**Comment by josef-pkt** [comment]
modified classes (again), mixed and penalized mixins

location choice: generic `modified.py` or specific `mixed.py` and `penalized.py` in relevant subdirectories, e.g. genmod and discrete.

`PoissonMixed` is likely too generic or broad as name, 
`PoissonRandEff` is better if we only support random intercepts (by group/categorical indicators, one-way or two/multi-way) but no random slopes.
 
RandEff is needed for item response models.


other issue: extensions based on stalled, abandoned python packages, e.g. extreme value theory, item response theory
(sem structural equation models is too large)

EVT needs multi-link models
IRT needs more mixed/random effects models.

**Comment by josef-pkt** [comment]
PRs to review and merge

prio-high, prio-elev:

- [ ] prio-high #9047
- [ ] prio-high #9175
- [ ] #8578
- [ ] #9181
- [ ] #8733
- [ ] #8812
- [ ] #8975
- [ ] status ? #7636
- [ ] #5490
- [ ] needs literature review #8958
- [ ] ...

4 additional old PRs with type-bug, 0 with type-bug-wrong

other PRs:
many PRs without labels, that I guess I never looked at those closely enough

- [ ] #9264
- [ ] looks good, no comments yet #9039
- [ ] unfinished, check or close #8817
- [ ] close this? #8715
- [ ] ...

**Comment by josef-pkt** [comment]
we have 22 issues with prio-high
12 PR with prio-elev

208 (!?) issues with bug label, 48 of those with 0.15 milestone
5 issues with bug-wrong label, we need to check if those still are "bug-wrong"  
(e.g. AFAIR, Probit for continuous data raises now exception or warning)

**Comment by theAeon** [comment]
if you could throw a windows arm build on the pile that would be awesome. It seems to work and build as is on head.

**Comment by bashtage** [comment]
Looks like it is only the roadmap for SciPy 1.17.
