### ISSUE TITLE
release 0.6

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#912]
ticket to keep milestone 0.6 open

What should still go into 0.6? What needs to be fixed?

update release notes and docs

**open PR or issues**

- [ ] GEE
  - [x] #1694
- [ ] Mixed
  - [x] #1695
- [ ] PHReg, Survival
  - [x] #1312
  - [ ] ~~survival2~~
- [ ] ~~GMM~~
- [ ] ~~Robust~~
  - [ ]  takes too much time to review
- [ ] discrete
  - [ ] 
- [ ] ~~Nonparametric~~
  - [ ] several by Padarn
- [ ] Stats
- [ ] Graphics
- [ ] general, base
- [x] MixedLM wrapper #1990

I changed the milestone to 0.7 on several PRs

**Bugs**

- [x] #1927 PR ready
- [x] #1929
- [ ] #1433  probplot ?
- [x] #1969  pacf conf_int
- [x] #1434 bootstrap in GenericLikelihood
- [x] #1901 numpy compat
- [x] #1981 api for GEE covstruct
- [x] #1991 GEE.from_formula does not handle exposure/offset

and a few more PRs left with milestone 0.6

---

items to check that they are in release notes

- sequence of PRs with bug fixes, refactorings in GLM, especially offset and exposure #1734
