### ISSUE TITLE
ENH roadmap outlier robust GLM, Poisson, Logit, asymmetric MLE

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#9148]
- [ ] RobGLM: M-estimator explicit for logit, Poisson and Gamma
   - explicit formulas for expectation exist for those 3 distributions. good summary and formulas in Heritier et al ch.5 and appendix 5
- [ ] generic computation, approximation of fisher correction term, e.g. https://github.com/statsmodels/statsmodels/issues/9146#issuecomment-1937772979
- [ ] bias correction, mentioned in Heritier et al ch. 5 referring to Dupuis and Morgenthaler 2002
- [ ] trimmed likelihood, with or without fisher correction
- [ ] high breakdown, redescending norm functions
- [ ] ...

tbc

Heritier, Stephane, Eva Cantoni, Samuel Copt, and Maria-Pia Victoria-Feser. Robust Methods in Biostatistics. Wiley Series in Probability and Statistics. Chichester, UK: John Wiley & Sons, Ltd, 2009. https://doi.org/10.1002/9780470740538.
 
Dupuis, Debbie J., and Stephan Morgenthaler. “Robust Weighted Likelihood Estimators with an Application to Bivariate Extreme Value Problems.” Canadian Journal of Statistics 30, no. 1 (2002): 17–36. https://doi.org/10.2307/3315863.
