### ISSUE TITLE
ENH/DOC/SUMM roadmap  t_test, wald_test in models 

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#9416]
#3676 laundry list related to hypothesis testing in models

This issue is for immediate improvements

- [ ] missing overview notebook
- docstrings and related
  - [ ] results classes are not in docs, need better list of content,, e.g. `WaldTestResults` in https://www.statsmodels.org/stable/generated/statsmodels.discrete.discrete_model.LogitResults.wald_test_terms.html https://stackoverflow.com/questions/66483143/extract-values-from-waldtestresults-pandas-dataframe
- [ ] review test results classes 
  example code comment in WaldTestResults mentions it is a stub
- [ ] multiple pvalue correction: 
   - [ ] t_test_multi not in docs, not public ? 
   - [ ] function to add it to existing `t_test`, missing?
     t_test_pairwise includes multiple p-value correction
- noncentrality
  - [ ] contrast wald_test_noncent and wald_test_noncent_generic: are those supposed to be public functions
  - [ ] ENH: support for power e.g. #1758
- [ ] ...
- [ ] ...
- [ ] ENH nonlinear wald test, currently private
- [ ] ...

current generic methods in `base.model` for wald tests:

- t_test
- t_test_pairwise
- wald_test
- wald_test_terms
- f_test (linear regression only) 
- _get_wald_nonlinear  private method in LikelihoodModelResults

helper function and results classes

- `LinearConstraints`  in base._constraints added to allow pickling (in contrast to patsy)
- stats.contrast module contains results classes for tests
  - _offset_constraint what is this? used only in one unit test 

other

- TransformRestriction in base._constraints  used by fit_constrained
- tools.linalg.transf_constraints  similar function used in GAM

Aside:
I just found `statsmodels.stats.tests.test_oneway.test_ols_noncentrality` which is the only user of `_offset_constraint`.
I don't remember this but it looks interesting with noncentrality and power computation for oneway test in OLS.
